/**
 * ============================================================================
 *  BACKDROP SETTINGS -- the knobs you are most likely to want to change.
 * ============================================================================
 *
 *  WATER_OPACITY, just below, is the one to reach for. 0 shows the photograph
 *  alone; 1 lets the rendered cascade hide the photographed one entirely.
 *
 *  To use a different photo, do NOT edit the region numbers by hand. Outline
 *  the cascade in any image editor, save the outlined and clean versions, and
 *  run:
 *
 *      .venv/bin/python scripts/measure_region.py "~/Downloads/waterfall area.png" \
 *          --plain "~/Downloads/jungle waterfall.png"
 *
 *  That measures the outline, rebuilds the cutout mask, installs both images
 *  and rewrites FALL_REGION below. Then confirm with:
 *
 *      npx playwright test -g "sits on the photographed"
 * ============================================================================
 */

/** How completely the rendered cascade covers the photographed one.
 *
 * At 1 the picture's own white water is entirely hidden: the photograph
 * supplies the shape and the setting, and every drop you see is generated and
 * carries the colour of the sound.
 *
 * Lower it to let the photographed water show through and blend with the tint.
 * Around 0.5 reads as the two being one body of water; below about 0.25 the
 * colour -- the entire point of the app -- stops being legible. */
export const WATER_OPACITY = 1;

/** How slowly the water falls at the quietest level, as a fraction of full speed.
 *
 * Level changes the pace of the cascade and nothing else about its shape: the
 * waterfall is the same width and the same density whether the sound is loud or
 * quiet, it just falls more gently. Never 0, so the water never freezes. */
export const LEVEL_SPEED_FLOOR = 0.28;

/** How white the outer edge of the cascade goes, 0 = no change, 1 = pure white.
 *
 * Real falling water throws spray at its edges, so a hard boundary between full
 * colour and bare rock reads as a cut-out. Lightening the rim lets it settle
 * into the picture. */
export const EDGE_FADE = 1.0;

/** How far in the fade reaches before the water is fully opaque.
 *
 * Expressed against the mask's baked distance channel, where 1.0 is half the
 * cascade's width -- so 0.14 finishes the blend about a fourteenth of the width
 * in from either side. Larger lets more of the photograph through; smaller
 * sharpens the edge back into a line. */
export const EDGE_BLEND = 0.24;

/** How high the spray throws off the base, as a fraction of the cascade's width.
 *
 * Kept low so the droplets hug the rocks the water lands on. The arc used to
 * peak at roughly a quarter of the cascade's width, which put the spray a good
 * way up the fall rather than at the foot of it. */
export const SPRAY_RISE = 0.20;

export const BACKDROP_SRC = "/jungle-waterfall.png";

/** Greyscale cutout of the cascade: white wherever water may be drawn.
 *
 * A waterfall is not a rectangle. This one narrows at the lip, widens on the
 * way down and spreads into the pool, so a rectangular region spills rendered
 * water onto the rocks either side. Generated by scripts/measure_region.py from
 * the outline in docs/reference/waterfall-area.png, and cropped to FALL_REGION
 * so the water plane's own UVs index it directly. */
export const MASK_SRC = "/waterfall-mask.png";

export const BACKDROP_WIDTH = 1046;
export const BACKDROP_HEIGHT = 1580;

/** Bounding box of the outlined cascade, as fractions of the image, y downward.
 *
 * Written by scripts/measure_region.py. Measured, not eyeballed -- nudging
 * these by hand until it "looks about right" is how the rendered cascade ends
 * up subtly off the photographed one in a way nobody can quite name. */
export const FALL_REGION = {
  left: 0.2352,
  right: 0.6902,
  top: 0.2082,
  bottom: 0.9873,
} as const;

export const FALL_WIDTH = FALL_REGION.right - FALL_REGION.left;
export const FALL_HEIGHT = FALL_REGION.bottom - FALL_REGION.top;
export const FALL_CENTER_X = (FALL_REGION.left + FALL_REGION.right) / 2;

/** The same region in camera space, where y counts upward from the bottom. */
export const FALL_TOP_Y = 1 - FALL_REGION.top;
export const FALL_BOTTOM_Y = 1 - FALL_REGION.bottom;
export const FALL_CENTER_Y = (FALL_TOP_Y + FALL_BOTTOM_Y) / 2;
